Milestone:Ruby Solo Project
shubhsk88/Methods-ruby pull request #3
Opened 2020-04-30 20:01 UTC by shubhsk88

This PR contains the implementations of the define methods in an array using the module functionality

2020-05-01 18:14 UTC, shshamim63 requested changes
## Status :traffic_light: Required Changes :tractor: 
___
Hi @shubhsk88 :wave: ,
amazing job :clap: well-indented code, returning enumerator based on the method name. Just found some issues, well they are easy to cover. Let's get to them and complete this project.
___
### :spades: Mandatory Changes :spades: 
___
1. The following methods are not covering some edge cases. Please check the comments attached to respective block of code.
- my_all?
- my_any?
- my_none?
- my_count
- my_inject
2. The multiply_els method is not placed on the proper position and needs to accept an array as a parameter. Check the comment.
3. You can brush up the readme, check out the comments.
4. You should not change the default configuration of linter files. Please check the comment also.
___
### :clubs: Optional Changes :clubs: 
___
I have refactored your my_map method. You can also refactor other methods too.
___
##### Please fix the above-mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/)

2020-05-01 18:14 UTC, shshamim63 commented on .rubocop.yml
> +  Max: 100
You should not alter the default configuration file. If you believe that default configuration is not enough please open an issue in this [link](https://github.com/microverseinc/linters-config/tree/master/ruby). If you think that some rules you want to disable for now you can use the inline disabled.

2020-05-01 18:14 UTC, shshamim63 commented on README.md
> +# Array-Method Ruby
They are enumerable methods. Not array methods. So you can name it more specific to the task that you have covered in here.

2020-05-01 18:14 UTC, shshamim63 commented on README.md
> +This Project showcases and implements the Array method of ruby using the Enumerable,The method represented in this project as follow
Did you mean something like this ->
`The project contains ruby enumerable methods. Where all the methods interact with an array and return the same value as the original method does. It covers the following enumerable methods.`

2020-05-01 18:14 UTC, shshamim63 commented on method.rb
> +  end
[Optional]
I just tried to refactor the code in the following way,
```ruby
def my_map(prop = nil)
    return to_enum(:my_map) unless block_given?
    new_arr = []
    my_each do |num|
      new_arr.push(prop ? prop.call(num) : yield(num))
    end
    new_arr
end
```

2020-05-01 18:14 UTC, shshamim63 commented on method.rb
> +  end
multiply_els is not an enumerable method, so it should be placed outside of the module. And based on the instruction it should seem something like following ->
```ruby
def multiply_els array
  array.my_inject { |acc, num| acc * num }
end
```

2020-05-01 18:14 UTC, shshamim63 commented on method.rb
> +  end
`my_inject` identical and returns the same thing as ruby's [`inject`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- combines all elements of enum by applying a binary operation, specified by a block
```ruby
[1, 2, 3].my_inject { |memo, num| memo + num } #should return 6
[1, 2, 3].my_inject(1) { |memo, num| memo + num } #should return 7
```
- when a symbol is specified combines each element of the collection by applying the symbol as a named method
```ruby
[1, 2, 3].my_inject(:+)  #should return 6
[1, 2, 3].my_inject(1, :+)  #should return 7
```

2020-05-01 18:14 UTC, shshamim63 commented on method.rb
> +  end
`my_count` identical and returns the same thing as ruby's [`count`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-count). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_count.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- counts the number of items in enum that are equal to item if an argument is given
```ruby
[1, 1, 2 ,3].my_count(1)  #should return 2
```

2020-05-01 18:14 UTC, shshamim63 commented on method.rb
> +  end
`my_none?` identical and returns the same thing as ruby's [`none?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-none-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_none.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- when a class is passed as an argument returns true if none of the collection is a member of such class
```ruby
[1, 2, 3].my_none?(String)  #should return true
['1', '2', '3'].my_none?(String)  #should return false
```
- when a Regex is passed as an argument returns true only if none of the collection matches the Regex
```ruby
%w[dog door rod blade].my_none?(/z/)   #should return true
%w[dog door rod blade].my_none?(/d/)   #should return false
```
- when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
```ruby
[1, 2, 4].my_none?(3) #should return true
[1, 2, 3].my_none?(3) #should return false
```

2020-05-01 18:14 UTC, shshamim63 commented on method.rb
> +  end
`my_any?` identical and returns the same thing as ruby's [`any?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-any-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_any.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- when a Regex is passed as an argument returns false if none of the collection matches the Regex
```ruby
%w[dog door rod blade].my_any?(/t/)    #should return false.
%w[dog door rod blade].my_any?(/d/)   #should return true.
```
- when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
```ruby
[1, 2, 3].my_any?(3)   #should return true
[1, 2, 2].my_any?(3)   #should return false
```

2020-05-01 18:14 UTC, shshamim63 commented on method.rb
> +  end
`my_all?` identical and returns the same thing as ruby's [`all?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-all-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_all.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2)) 
- when no block or argument is given, returns true when none of the collection members are false or nil
```ruby
[1, 2, 3].my_all? #should return true
[1, 2, nil].my_all? #should return false
[1, false, nil].my_all? #should return false
```
- when a class is passed as an argument returns true if all of the collection is a member of such class
```ruby
[1, 2, 3].my_all?(Integer) #should return true
[1, 2, nil].my_all?(Integer) #should return false
```
- when a Regex is passed as an argument returns true if all of the collection matches the Regex
```ruby
%w[dog door rod blade].my_all?(/d/)   #should return true.
%w[dog door rod blade].my_all?(/t/)   #should return false.
```

2020-05-04 03:49 UTC, uryelah requested changes
Hello **Shubham Singh**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all, good job with your code. It improved a lot from the first review 🌟**

There are still some issues to fix though. [Make sure you read the specifications of the enumerable module](https://ruby-doc.org/core-2.7.1/Enumerable.html) again with care and check the required changes in the comments below. You can do it! After you are done with this your ruby foundation will be solid as a rock!💪 

---------     

## Required Changes 🏗 👷‍♀ 

----

2020-05-04 03:49 UTC, uryelah commented on method.rb
> +      my_each do |num|
- [ ] When you don't give a block or argument to the my_all? method it should return true only if all of the enumerable items are 'truthy'.
So an array with a 'falsy' item should return false wit this method. [Read this article if you are not sure which are the falsy and truthy values in ruby.](https://andycroll.com/ruby/truthiness-in-conditionals/)
Fix the code inside your your else conditional to fix this.

2020-05-04 03:49 UTC, uryelah commented on method.rb
> +          stat = num.is_a?(arg)
- [ ] The stat should be true only if all of the items in the enumerable are of the given Class.
Make sure it returns false the first time if finds something that is not from the given Class.

2020-05-04 03:49 UTC, uryelah commented on method.rb
> +      if arg.class == Class
- [ ] Make sure the my_any also works when a pattern other than a Class or Regexp is given.
EX:
[0,1,'ok', [], false, 'lol'].any?('lol')
=> true

2020-05-04 03:49 UTC, uryelah commented on method.rb
> +        my_each do |num|
- [ ] Here you have the opposite issue you have on the my_all? method.
It should return false as soon as you find any item that is from the argument Class.
Ex:
[1,2,3,'work', true].none?(TrueClass)
=> false

2020-05-04 03:49 UTC, uryelah commented on method.rb
> +        end
- [ ] Remember to add a condition for a pattern other than a Class or a Regex.

2020-05-04 03:49 UTC, uryelah commented on method.rb
> +  def my_inject(acc = 0, sign = nil)
- [ ] my_inject should also be able to take a block.
Make sure it works with for example an array or strings and a block that adds only the strings longer than 3 characters.

2020-05-04 03:49 UTC, uryelah commented on method.rb
> +# p arr.my_all?{|num| num%2==0}
- [ ] Make sure to remove all of your commented out code before requesting a ode review.

2020-05-04 03:49 UTC, uryelah commented
**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-05-05 18:26 UTC, mosesogwo requested changes
**:+1: for all your efforts on this project. You have just a small case left to fix**
- **my_any?** - when no block or argument is given, my_any? should return true **only** if at least one of the elements is true (that is not false or nil).
e.g `[false, nil].my_any?` should return `false` and not `true`, since none of the elements is true.


_**Kindly fix this and submit another code review request.**_

**Cheers:stars:**

### Status: Changes Requested.

2020-05-06 13:08 UTC, Torres-ssf approved these changes
### Project Approved :clap: :clap: :clap: 
Hi there @shubhsk88 :hand: 
Your worked a lot on this project and should be proud of it :tada: :+1: 
You can merge the PR now. :smiley: 
Good luck with the next one

**Happy coding :computer:** 

**Sergio Torres**

2020-05-06 14:34 UTC, merged